FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    libboost-system1.74.0 \
    libboost-thread1.74.0 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY backend .
COPY inventory.json .
COPY sales_history.json .
COPY end_of_day_report_*.txt .

EXPOSE 18080

RUN chmod +x backend
CMD ["./backend"]
